### ISSUE TITLE
Try convert with fallback

### ISSUE THREAD

**Issue by weedkiller** [PoweredSoft/Types#2]
Hi, I am trying to load a CSV file and bind to a grid, perform data filtering etc. wondering if this might help.

In my case, since the CSV headers dont hold type information when I load and try to build an Iqueryable for a grid, the headers and data are always string.

This has me wondering, can it detect the type of the data on the columns, and fall back to string if it cant. This would allow the query to be richer, since if it knew it were date, then we could filter between dates etc. as opposed to being limited to string filters

**Comment by dlebee** [comment]
Will need an example project.

**Comment by dlebee** [comment]
@weedkiller no news

**Comment by weedkiller** [comment]
will share one with you later today

**Comment by weedkiller** [comment]
Hi, I dont know the types prior to loading

How to get the TypedList from the Excel Or CSV file? I dont know what the col types & headers are ahead of time. I need two things, 

1. How to read in a `List<>` getting the typea if possible or simply fall back to string.
2. and how to saved that as a to a Sql table at _runtime_

How do I get that DynamicListFromExcel?

`var dynamicListFromExcel= JsonConvert.DeserializeObject<List<DynamicListFromExcel>>(testData);`
_______
This helps create a table from CSV
```
 public static void CsvToDb(string file, string path, System.Data.Common.DbConnection _connection)
        {

            DataTable table = CommonEngine.CsvToDataTable(path, "ImportRecord", ',', true);

            using (var bulkCopy = new SqlBulkCopy(_connection.ConnectionString, SqlBulkCopyOptions.KeepIdentity))
            {
                
                foreach (DataColumn col in table.Columns)
                {
                    bulkCopy.ColumnMappings.Add(col.ColumnName, col.ColumnName);
                }

                bulkCopy.BulkCopyTimeout = 600;
                bulkCopy.DestinationTableName = file.ToString();
                bulkCopy.WriteToServer(table);
            }
        }
```

**Comment by dlebee** [comment]
this is unrelated to this project,
This project is just to offer how to convert type A to type B differently.

But I can answer your question a little,

If its csv well everything must be a string and you can use regex or logic to dermine using patterns of the raw string part if its a int, string, or date etc..

if you are using excel, using OpenXML SDK you probably have the data type of the column, in DataColumn.
